spring:
  profiles:
    active: dev
    group:
      dev: "dev,common"
      prod: "prod,common"

# common 配置
---
spring:
  config:
    activate:
      on-profile: "common"
  application:
    name: klbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
#    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/nblog?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8096
  servlet:
    context-path: /api

# 开发配置
---
spring:
  config:
    activate:
      on-profile: dev
  mvc:
    static-path-pattern: /resource/**
    view:
      suffix: /
      prefix: .html

  web:
    resources:
      static-locations: file:D://noodbImg/
#      static-locations: /home/web/klbc-blog/article-images/
      #因为打不了生产包所以用开发包试试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.noodb.blog.mapper: info
article:
  imagePath:

    /noodbImg/
#    /home/web/klbc-blog/article-images/


# 生产配置
---
spring:
  config:
    activate:
      on-profile: prod
article:
  imagePath:
    /home/web/klbc-blog/article-images/
